### ISSUE TITLE
Plugin version 2.1.0 is crashing will null pointer exception when generating report

### ISSUE THREAD

**Issue by lawrenceong** [albuch/sbt-dependency-check#145]
#### Describe the bug
Running `sbt dependencyCheck` with version 2.1.0 of the plugin is producing a null pointer exception when generating the report

#### Version of sbt-dependency-check used
The problem occurs using version 2.1.0 of the plugin.

#### Log file
Receiving the following stack trace when running `sbt dependencyCheck`
```
[error] Failed creating report: null
[error] java.lang.NullPointerException
[error] 	at org.owasp.dependencycheck.utils.FileUtils.getResourceAsFile(FileUtils.java:184)
[error] 	at org.owasp.dependencycheck.data.nvdcve.ConnectionFactory.updateSchema(ConnectionFactory.java:375)
[error] 	at org.owasp.dependencycheck.data.nvdcve.ConnectionFactory.ensureSchemaVersion(ConnectionFactory.java:445)
[error] 	at org.owasp.dependencycheck.data.nvdcve.ConnectionFactory.initialize(ConnectionFactory.java:193)
[error] 	at org.owasp.dependencycheck.data.nvdcve.ConnectionFactory.getConnection(ConnectionFactory.java:234)
[error] 	at org.owasp.dependencycheck.data.nvdcve.CveDB.open(CveDB.java:269)
[error] 	at org.owasp.dependencycheck.data.nvdcve.CveDB.<init>(CveDB.java:239)
[error] 	at org.owasp.dependencycheck.Engine.openDatabase(Engine.java:969)
[error] 	at org.owasp.dependencycheck.Engine.doUpdates(Engine.java:845)
[error] 	at org.owasp.dependencycheck.Engine.initializeAndUpdateDatabase(Engine.java:662)
[error] 	at org.owasp.dependencycheck.Engine.analyzeDependencies(Engine.java:592)
[error] 	at net.vonbuchholtz.sbt.dependencycheck.DependencyCheckPlugin$.createReport(DependencyCheckPlugin.scala:571)
[error] 	at net.vonbuchholtz.sbt.dependencycheck.DependencyCheckPlugin$.$anonfun$checkTask$6(DependencyCheckPlugin.scala:325)
[error] 	at net.vonbuchholtz.sbt.dependencycheck.DependencyCheckPlugin$.withEngine(DependencyCheckPlugin.scala:591)
[error] 	at net.vonbuchholtz.sbt.dependencycheck.DependencyCheckPlugin$.$anonfun$checkTask$2(DependencyCheckPlugin.scala:323)
[error] 	at net.vonbuchholtz.sbt.dependencycheck.DependencyCheckPlugin$.$anonfun$checkTask$2$adapted(DependencyCheckPlugin.scala:286)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:40)
[error] 	at sbt.std.Transform$$anon$4.work(System.scala:67)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:269)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error] 	at sbt.Execute.work(Execute.scala:278)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:269)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[error] 	at java.base/java.lang.Thread.run(Thread.java:834)
[error] (dependencyCheck) java.lang.NullPointerException
[error] Total time: 3 s, completed 5 Nov. 2020, 7:55:39 pm
```
#### To Reproduce
1. Create a blank Scala sbt project with IntelliJ Idea.  Tested with Scala 2.12.12, sbt 1.2.8 on AdoptOpenJdk 11.
2. Add the plugin version 2.0.0 in `project/plugins.sbt` and run `sbt dependencyCheck`.  This is successful.
3. Replace plugin with version 2.1.0.  Run `sbt dependencyCheck`.  This fails with the error above.

#### Expected behavior
A report is created without the null pointer exception.

**Comment by albuch** [comment]
Hi @lawrenceong,
are you using a custom data directory or other than the default h2 database?
Did you run `dependencyCheckPurge` once after the upgrade before running the check  as mentioned in the release notes?

**Comment by albuch** [comment]
Hi @lawrenceong I just reproduced the issue and purging the database before running the first time v2.1.0, as noted in the release notes, should fix this.
However the `dependencyCheckPurge` task seems to somehow have a bug that produces a wrong path to delete and therefore throws an error.

In the meantime until a bugfix is released you can manually delete the data folder which is located at `~/.ivy/cache/org.owasp/dependency-check-utils/jars/data` if not overridden `dependencyCheckDataDirectory`. After that the task runs without error.

**Comment by lawrenceong** [comment]
Thanks @albuch.  Can confirm that after deleting the data directory `~/.ivy2/cache/org.owasp/dependency-check-utils`, it works.  I did try the `dependencyCheckPurge` and got:

```
[error] Unable to delete '.../.ivy2/cache/org.owasp/dependency-check-utils/jars/data/dc.h2.db'; the database file does not exists
```

Thought that means I don't have any obsolete data, so ignored it as a noop.
