### ISSUE TITLE
How do I add the database driver to the classpath?

### ISSUE THREAD

**Issue by VeryBueno** [albuch/sbt-dependency-check#49]
Hello, I added the plugin to `project/plugins.sbt`. In my `build.sbt` I have the following:

```
libraryDependencies ++= Seq(
  "com.oracle.jdbc" % "ojdbc8" % "12.2.0.1"
)

dependencyCheckDatabaseDriverName := Some("oracle.jdbc.OracleDriver")
dependencyCheckConnectionString := Some("jdbc_url")
dependencyCheckDatabaseUser := Some("my_username")
dependencyCheckDatabasePassword := Some("my_password")
dependencyCheckAutoUpdate := Some(false)
```

The `ojdbc8` library provides the `oracle.jdbc.OracleDriver`, but I get this error:

````
[info] Applying project settings to DependencyCheck settings
[info] Running check for myproject
16:28:09.309 [pool-6-thread-1] ERROR o.o.d.Engine - Unable to load database driver

Unable to connect to the dependency-check database.
[error] Failed creating report: Unable to connect to the dependency-check database.
[error] 	Unable to load database driver
org.owasp.dependencycheck.exception.ExceptionCollection: Unable to connect to the dependency-check database.
	Unable to load database driver
	at org.owasp.dependencycheck.Engine.throwFatalExceptionCollection(Engine.java:1095)
	at org.owasp.dependencycheck.Engine.initializeAndUpdateDatabase(Engine.java:742)
	at org.owasp.dependencycheck.Engine.analyzeDependencies(Engine.java:642)
	at net.vonbuchholtz.sbt.dependencycheck.DependencyCheckPlugin$.createReport(DependencyCheckPlugin.scala:466)
	at net.vonbuchholtz.sbt.dependencycheck.DependencyCheckPlugin$$anonfun$checkTask$1$$anonfun$apply$3$$anonfun$apply$5.apply(DependencyCheckPlugin.scala:270)
	at net.vonbuchholtz.sbt.dependencycheck.DependencyCheckPlugin$$anonfun$checkTask$1$$anonfun$apply$3$$anonfun$apply$5.apply(DependencyCheckPlugin.scala:268)
	at net.vonbuchholtz.sbt.dependencycheck.DependencyCheckPlugin$.net$vonbuchholtz$sbt$dependencycheck$DependencyCheckPlugin$$withEngine(DependencyCheckPlugin.scala:486)
	at net.vonbuchholtz.sbt.dependencycheck.DependencyCheckPlugin$$anonfun$checkTask$1$$anonfun$apply$3.apply(DependencyCheckPlugin.scala:268)
	at net.vonbuchholtz.sbt.dependencycheck.DependencyCheckPlugin$$anonfun$checkTask$1$$anonfun$apply$3.apply(DependencyCheckPlugin.scala:232)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[error] (*:dependencyCheck) org.owasp.dependencycheck.exception.ExceptionCollection: Unable to connect to the dependency-check database.
[error] 	Unable to load database driver
[error] Total time: 1 s, completed Aug 21, 2018 4:28:09 PM

Process finished with exit code 1
````

How do I make the driver included in my `libraryDependencies` available to the `dependencyCheck` task?

**Comment by albuch** [comment]
Untested: you should add the dependency on the database driver in your `plugins.sbt` instead of `build.sbt` so that it will be available to the classpath of the plugin execution.

```
addSbtPlugin("net.vonbuchholtz" % "sbt-dependency-check" % "2.8.0")
libraryDependencies += "com.oracle.jdbc" % "ojdbc8" % "12.2.0.1"
``` 
See https://www.scala-sbt.org/1.0/docs/Plugins.html#Using+an+auto+plugin for details on how to use sbt Auto Plugins.
