### ISSUE TITLE
No support for JSON feeds, XML feeds are being deprecated

### ISSUE THREAD

**Issue by cmholley** [albuch/sbt-dependency-check#69]
I do not see support in the documentation for the new [JSON based NVE feeds](https://nvd.nist.gov/vuln/data-feeds#JSON_FEED). According to [XML Vulnerability Feed Retirement Update](https://nvd.nist.gov/General/News/XML-Vulnerability-Feed-Retirement) the XML feeds will not be supported. When trying to run with the JSON feeds, I get the following error. I am running v0.2.10

```scala
[error] Failed creating report: One or more exceptions occurred during dependency-check analysis
[error] 	com.sun.org.apache.xerces.internal.impl.io.MalformedByteSequenceException: Invalid byte 1 of 1-byte UTF-8 sequence.
[error] org.owasp.dependencycheck.exception.ExceptionCollection: One or more exceptions occurred during dependency-check analysis
[error] 	com.sun.org.apache.xerces.internal.impl.io.MalformedByteSequenceException: Invalid byte 1 of 1-byte UTF-8 sequence.
[error] 	at org.owasp.dependencycheck.Engine.analyzeDependencies(Engine.java:693)
[error] 	at net.vonbuchholtz.sbt.dependencycheck.DependencyCheckPlugin$.createReport(DependencyCheckPlugin.scala:470)
[error] 	at net.vonbuchholtz.sbt.dependencycheck.DependencyCheckPlugin$.$anonfun$checkTask$9(DependencyCheckPlugin.scala:274)
[error] 	at net.vonbuchholtz.sbt.dependencycheck.DependencyCheckPlugin$.withEngine(DependencyCheckPlugin.scala:490)
[error] 	at net.vonbuchholtz.sbt.dependencycheck.DependencyCheckPlugin$.$anonfun$checkTask$2(DependencyCheckPlugin.scala:272)
[error] 	at net.vonbuchholtz.sbt.dependencycheck.DependencyCheckPlugin$.$anonfun$checkTask$2$adapted(DependencyCheckPlugin.scala:236)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:39)
[error] 	at sbt.std.Transform$$anon$4.work(System.scala:66)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:262)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error] 	at sbt.Execute.work(Execute.scala:271)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:262)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:174)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:36)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] (dependencyCheck) org.owasp.dependencycheck.exception.ExceptionCollection: One or more exceptions occurred during dependency-check analysis
[error] 	com.sun.org.apache.xerces.internal.impl.io.MalformedByteSequenceException: Invalid byte 1 of 1-byte UTF-8 sequence.
[error] Total time: 11 s, completed May 7, 2019 11:51:27 AM

```

Are there plans to add support for the JSON feeds?

**Comment by albuch** [comment]
Yes, once [OWASP DependencyCheck](https://github.com/jeremylong/DependencyCheck) v5.0.0 is released (currently 5.0.0-M3) the sbt plugin will upgrade the core library and support JSON feeds as well.

**Comment by ghostbuster91** [comment]
I tried to use `sbt-dependency-check`, but it is unable to fetch data from NVE. I don't know but it might be connected with xml based data being deprecated?

Here is my log:
```
> sbt dependencyCheck                       
[info] Loading settings for project global-plugins from idea.sbt ...
[info] Loading global plugins from /home/*/.sbt/1.0/plugins
[info] Loading settings for project **** from plugins.sbt ...
[info] Loading project definition from ***
[info] Loading settings for project rootProject from build.sbt,version.sbt ...
[info] Set current project to ****
[info] Applying project settings to DependencyCheck settings
[info] Applying project settings to DependencyCheck settings
[info] Running check for****
[error] Failed creating report: One or more exceptions occurred during dependency-check analysis
[error]         The download was interrupted; unable to complete the update
[info] Running check for core
12:47:03.882 [pool-43-thread-3] ERROR org.owasp.dependencycheck.utils.Downloader - IO Exception connecting to https://nvd.nist.gov/feeds/xml/cve/2.0/nvdcve-2.0-2008.xml.gz: HEAD request returned a non-200 status code: https://nvd.nist.gov/feeds/xml/cve/2.0/nvdcve-2.0-2008.xml.gz
12:47:03.885 [pool-43-thread-1] ERROR org.owasp.dependencycheck.utils.Downloader - IO Exception connecting to https://nvd.nist.gov/feeds/xml/cve/2.0/nvdcve-2.0-2018.xml.gz: HEAD request returned a non-200 status code: https://nvd.nist.gov/feeds/xml/cve/2.0/nvdcve-2.0-2018.xml.gz
12:47:03.895 [pool-43-thread-4] ERROR org.owasp.dependencycheck.utils.Downloader - IO Exception connecting to https://nvd.nist.gov/feeds/xml/cve/2.0/nvdcve-2.0-2007.xml.gz: HEAD request returned a non-200 status code: https://nvd.nist.gov/feeds/xml/cve/2.0/nvdcve-2.0-2007.xml.gz
12:47:03.903 [pool-43-thread-6] ERROR org.owasp.dependencycheck.utils.Downloader - IO Exception connecting to https://nvd.nist.gov/feeds/xml/cve/2.0/nvdcve-2.0-2010.xml.gz: HEAD request returned a non-200 status code: https://nvd.nist.gov/feeds/xml/cve/2.0/nvdcve-2.0-2010.xml.gz
12:47:03.904 [pool-43-thread-7] ERROR org.owasp.dependencycheck.utils.Downloader - IO Exception connecting to https://nvd.nist.gov/feeds/xml/cve/2.0/nvdcve-2.0-2011.xml.gz: HEAD request returned a non-200 status code: https://nvd.nist.gov/feeds/xml/cve/2.0/nvdcve-2.0-2011.xml.gz
12:47:03.926 [pool-43-thread-5] ERROR org.owasp.dependencycheck.utils.Downloader - IO Exception connecting to https://nvd.nist.gov/feeds/xml/cve/2.0/nvdcve-2.0-2002.xml.gz: HEAD request returned a non-200 status code: https://nvd.nist.gov/feeds/xml/cve/2.0/nvdcve-2.0-2002.xml.gz
12:47:03.929 [pool-43-thread-16] ERROR org.owasp.dependencycheck.utils.Downloader - IO Exception connecting to https://nvd.nist.gov/feeds/xml/cve/2.0/nvdcve-2.0-2015.xml.gz: HEAD request returned a non-200 status code: https://nvd.nist.gov/feeds/xml/cve/2.0/nvdcve-2.0-2015.xml.gz
12:47:03.929 [pool-43-thread-17] ERROR org.owasp.dependencycheck.utils.Downloader - IO Exception connecting to https://nvd.nist.gov/feeds/xml/cve/2.0/nvdcve-2.0-2017.xml.gz: HEAD request returned a non-200 status code: https://nvd.nist.gov/feeds/xml/cve/2.0/nvdcve-2.0-2017.xml.gz
12:47:03.930 [pool-43-thread-18] ERROR org.owasp.dependencycheck.utils.Downloader - IO Exception connecting to https://nvd.nist.gov/feeds/xml/cve/2.0/nvdcve-2.0-2019.xml.gz: HEAD request returned a non-200 status code: https://nvd.nist.gov/feeds/xml/cve/2.0/nvdcve-2.0-2019.xml.gz
12:47:03.936 [pool-43-thread-10] ERROR org.owasp.dependencycheck.utils.Downloader - IO Exception connecting to https://nvd.nist.gov/feeds/xml/cve/2.0/nvdcve-2.0-2005.xml.gz: HEAD request returned a non-200 status code: https://nvd.nist.gov/feeds/xml/cve/2.0/nvdcve-2.0-2005.xml.gz
12:47:03.936 [pool-43-thread-11] ERROR org.owasp.dependencycheck.utils.Downloader - IO Exception connecting to https://nvd.nist.gov/feeds/xml/cve/2.0/nvdcve-2.0-2006.xml.gz: HEAD request returned a non-200 status code: https://nvd.nist.gov/feeds/xml/cve/2.0/nvdcve-2.0-2006.xml.gz
12:47:03.937 [pool-43-thread-2] ERROR org.owasp.dependencycheck.utils.Downloader - IO Exception connecting to https://nvd.nist.gov/feeds/xml/cve/2.0/nvdcve-2.0-2009.xml.gz: HEAD request returned a non-200 status code: https://nvd.nist.gov/feeds/xml/cve/2.0/nvdcve-2.0-2009.xml.gz
12:47:03.937 [pool-43-thread-9] ERROR org.owasp.dependencycheck.utils.Downloader - IO Exception connecting to https://nvd.nist.gov/feeds/xml/cve/2.0/nvdcve-2.0-2003.xml.gz: HEAD request returned a non-200 status code: https://nvd.nist.gov/feeds/xml/cve/2.0/nvdcve-2.0-2003.xml.gz
12:47:03.937 [pool-43-thread-8] ERROR org.owasp.dependencycheck.utils.Downloader - IO Exception connecting to https://nvd.nist.gov/feeds/xml/cve/2.0/nvdcve-2.0-2004.xml.gz: HEAD request returned a non-200 status code: https://nvd.nist.gov/feeds/xml/cve/2.0/nvdcve-2.0-2004.xml.gz
12:47:03.938 [pool-43-thread-15] ERROR org.owasp.dependencycheck.utils.Downloader - IO Exception connecting to https://nvd.nist.gov/feeds/xml/cve/2.0/nvdcve-2.0-2013.xml.gz: HEAD request returned a non-200 status code: https://nvd.nist.gov/feeds/xml/cve/2.0/nvdcve-2.0-2013.xml.gz
12:47:03.938 [pool-43-thread-14] ERROR org.owasp.dependencycheck.utils.Downloader - IO Exception connecting to https://nvd.nist.gov/feeds/xml/cve/2.0/nvdcve-2.0-2012.xml.gz: HEAD request returned a non-200 status code: https://nvd.nist.gov/feeds/xml/cve/2.0/nvdcve-2.0-2012.xml.gz
12:47:03.938 [pool-43-thread-12] ERROR org.owasp.dependencycheck.utils.Downloader - IO Exception connecting to https://nvd.nist.gov/feeds/xml/cve/2.0/nvdcve-2.0-2014.xml.gz: HEAD request returned a non-200 status code: https://nvd.nist.gov/feeds/xml/cve/2.0/nvdcve-2.0-2014.xml.gz
12:47:03.939 [pool-43-thread-13] ERROR org.owasp.dependencycheck.utils.Downloader - IO Exception connecting to https://nvd.nist.gov/feeds/xml/cve/2.0/nvdcve-2.0-2016.xml.gz: HEAD request returned a non-200 status code: https://nvd.nist.gov/feeds/xml/cve/2.0/nvdcve-2.0-2016.xml.gz
12:47:04.624 [pool-43-thread-3] ERROR org.owasp.dependencycheck.utils.Downloader - IO Exception connecting to https://nvd.nist.gov/feeds/xml/cve/2.0/nvdcve-2.0-2008.xml.gz: GET request returned a non-200 status code: https://nvd.nist.gov/feeds/xml/cve/2.0/nvdcve-2.0-2008.xml.gz
12:47:04.624 [pool-43-thread-1] ERROR org.owasp.dependencycheck.utils.Downloader - IO Exception connecting to https://nvd.nist.gov/feeds/xml/cve/2.0/nvdcve-2.0-Modified.xml.gz: GET request returned a non-200 status code: https://nvd.nist.gov/feeds/xml/cve/2.0/nvdcve-2.0-Modified.xml.gz
12:47:04.891 [pool-7-thread-1] ERROR org.owasp.dependencycheck.analyzer.AssemblyAnalyzer - ----------------------------------------------------
12:47:04.891 [pool-7-thread-1] ERROR org.owasp.dependencycheck.analyzer.AssemblyAnalyzer - .NET Assembly Analyzer could not be initialized and at least one 'exe' or 'dll' was scanned. The 'mono' executable could not be found on the path; either disable the Assembly Analyzer or configure the path mono. On some systems mono-runtime and mono-devel need to be installed.
12:47:04.891 [pool-7-thread-1] ERROR org.owasp.dependencycheck.analyzer.AssemblyAnalyzer - ----------------------------------------------------
[error] Failed creating report: One or more exceptions occurred during dependency-check analysis
[error]         Unable to download the NVD CVE data.
[error] org.owasp.dependencycheck.exception.ExceptionCollection: One or more exceptions occurred during dependency-check analysis
[error]         Unable to download the NVD CVE data.
[error]         at org.owasp.dependencycheck.Engine.analyzeDependencies(Engine.java:693)
[error]         at net.vonbuchholtz.sbt.dependencycheck.DependencyCheckPlugin$.createReport(DependencyCheckPlugin.scala:470)
[error]         at net.vonbuchholtz.sbt.dependencycheck.DependencyCheckPlugin$.$anonfun$checkTask$9(DependencyCheckPlugin.scala:274)
[error]         at net.vonbuchholtz.sbt.dependencycheck.DependencyCheckPlugin$.withEngine(DependencyCheckPlugin.scala:490)
[error]         at net.vonbuchholtz.sbt.dependencycheck.DependencyCheckPlugin$.$anonfun$checkTask$2(DependencyCheckPlugin.scala:272)
[error]         at net.vonbuchholtz.sbt.dependencycheck.DependencyCheckPlugin$.$anonfun$checkTask$2$adapted(DependencyCheckPlugin.scala:236)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:40)
[error]         at sbt.std.Transform$$anon$4.work(System.scala:67)
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:269)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error]         at sbt.Execute.work(Execute.scala:278)
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:269)
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error]         at java.lang.Thread.run(Thread.java:748)
[error] org.owasp.dependencycheck.exception.ExceptionCollection: One or more exceptions occurred during dependency-check analysis
[error]         The download was interrupted; unable to complete the update
[error]         at org.owasp.dependencycheck.Engine.analyzeDependencies(Engine.java:693)
[error]         at net.vonbuchholtz.sbt.dependencycheck.DependencyCheckPlugin$.createReport(DependencyCheckPlugin.scala:470)
[error]         at net.vonbuchholtz.sbt.dependencycheck.DependencyCheckPlugin$.$anonfun$checkTask$9(DependencyCheckPlugin.scala:274)
[error]         at net.vonbuchholtz.sbt.dependencycheck.DependencyCheckPlugin$.withEngine(DependencyCheckPlugin.scala:490)
[error]         at net.vonbuchholtz.sbt.dependencycheck.DependencyCheckPlugin$.$anonfun$checkTask$2(DependencyCheckPlugin.scala:272)
[error]         at net.vonbuchholtz.sbt.dependencycheck.DependencyCheckPlugin$.$anonfun$checkTask$2$adapted(DependencyCheckPlugin.scala:236)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:40)
[error]         at sbt.std.Transform$$anon$4.work(System.scala:67)
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:269)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error]         at sbt.Execute.work(Execute.scala:278)
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:269)
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error]         at java.lang.Thread.run(Thread.java:748)
[error] (core / dependencyCheck) org.owasp.dependencycheck.exception.ExceptionCollection: One or more exceptions occurred during dependency-check analysis
[error]         Unable to download the NVD CVE data.
[error] (dependencyCheck) org.owasp.dependencycheck.exception.ExceptionCollection: One or more exceptions occurred during dependency-check analysis
[error]         The download was interrupted; unable to complete the update
[error] Total time: 14 s, completed May 21, 2019 12:47:05 PM
```

**Comment by albuch** [comment]
Hi @ghostbuster91, it seems you're hitting the rate limiting of the NVD feed. You should consider setting up your own mirror of the feeds for build stability. Check out https://github.com/stevespringett/nist-data-mirror for a start. 
See https://github.com/jeremylong/DependencyCheck/issues/1558 for more information and upcoming mitigation in v5.0.0 release of DependencyCheck.

**Comment by ghostbuster91** [comment]
Hi @albuch I'm not sure if it's the rate limiting thing since it was my first run of sbt-dependency-check

**Comment by albuch** [comment]
@ghostbuster91 DependencyCheck downloads several feed files in parallel, so rate limiting already might apply during your first run. This might be escalated if your identified with an enterprise wide IP address for outgoing traffic and other project/build jobs within your corporate network have downloaded the feed recently.

With the next release ob the sbt plugin there will be a default limit of 2 parallel downloads to mitigate the issue, however to be fully independent of rate limiting and network/connectivity issues you should consider setting up an internal mirror as mentioned earlier.
